QUESTIONS = [
    "Question: What is the primary purpose of a firewall in computer networks?\nOptions:\nA) To encrypt data transmissions\nB) To prevent unauthorized access\nC) To boost network speed\nD) To detect hardware failures\nCorrect Answer: B) To prevent unauthorized access\nProvide a precise and concise rationale for the correct answer.",
    "Question: How does encryption contribute to data security?\nOptions:\nA) It slows down data transmission\nB) It protects data from unauthorized access\nC) It increases hardware failures\nD) It hampers network speed\nCorrect Answer: B) It protects data from unauthorized access\nExplain briefly the role of encryption in data security.",
    "Question: What is the purpose of a VPN in networking?\nOptions:\nA) To expose network vulnerabilities\nB) To ensure slow network connections\nC) To create secure, private connections\nD) To enhance hardware failures\nCorrect Answer: C) To create secure, private connections\nProvide a concise rationale for VPN's role in networking.",
    "Question: Why is multi-factor authentication essential?\nOptions:\nA) It decreases security risks\nB) It simplifies access control\nC) It adds an extra layer of security\nD) It limits network access\nCorrect Answer: C) It adds an extra layer of security\nBriefly explain the importance of multi-factor authentication.",
    "Question: How do intrusion detection systems contribute to network security?\nOptions:\nA) They slow down network performance\nB) They prevent all types of attacks\nC) They identify and respond to suspicious activities\nD) They boost network speed\nCorrect Answer: C) They identify and respond to suspicious activities\nExplain the role of intrusion detection systems in network security.",
    "Question: What is the primary function of an antivirus program?\nOptions:\nA) To introduce malware\nB) To protect against malware\nC) To encrypt data transmissions\nD) To enhance hardware failures\nCorrect Answer: B) To protect against malware\nProvide a brief rationale for the necessity of antivirus programs.",
    "Question: Why is regular software patching important in network security?\nOptions:\nA) It increases vulnerability\nB) It enhances system performance\nC) It reduces security risks\nD) It impacts network speed\nCorrect Answer: C) It reduces security risks\nBriefly explain the significance of regular software patching in network security.",
    "Question: What role does a proxy server play in network security?\nOptions:\nA) It exposes IP addresses\nB) It hides IP addresses\nC) It reduces network performance\nD) It boosts network speed\nCorrect Answer: B) It hides IP addresses\nExplain the purpose of a proxy server in network security.",
    "Question: How does a DDoS attack impact network operations?\nOptions:\nA) It enhances network speed\nB) It overloads systems, causing disruption\nC) It reduces the risk of data breaches\nD) It improves hardware performance\nCorrect Answer: B) It overloads systems, causing disruption\nBriefly explain the impact of a DDoS attack on network operations.",
    "Question: Why is access control essential for network security?\nOptions:\nA) It restricts authorized access\nB) It facilitates unrestricted access\nC) It complicates network management\nD) It slows down hardware performance\nCorrect Answer: A) It restricts authorized access\nProvide a concise rationale for the importance of access control in network security.",
]
